\newpage
# Introducción {#intro}

El **Reconocimiento de Entidades Nombradas** (_NER_) es una subtarea de extracción de información que busca ubicar las menciones de **entidades nombradas** en textos no estructurados. Estas entidades son luego clasificadas en categorías predefinidas como los nombres de personas, organizaciones, ubicaciones, expresiones de tiempo, cantidades, valores monetarios, porcentajes, entre otras.

Por ejemplo en el siguiente texto:

>Este es el proyecto final de carrera de los alumnos Gómez y Orsay para el Instituto Tecnológico de Buenos Aires.

Se pueden detectar 3 entidades:

* **Gómez**: Persona
* **Orsay**: Persona
* **Instituto Tecnológico de Buenos Aires**: Organización

El estado-del-arte de los sistemas _NER_ producen un rendimiento casi humano[@marsh-perzanowski-1998-muc] (cercanos al 95% de _valor-F_).

A pesar de estos altos valores de rendimiento, la industria tiene dificultades para poder capitalizar la efectividad de dichas sistemas y algoritmos.
Es por ello que en este trabajo final hemos tomado la decisión de implementar una plataforma Open Source para revertir esta situación.
