--- 
title: "NERd: anotador eficiente de modelos estadísticos para el reconocimiento de entidades nombradas"
subtitle: Instituto Tecnológico de Buenos Aires
author:
  - Horacio Miguel Gómez $(L:50825)$
  - Juan Pablo Orsay $(L:49373)$
  - Lic. Diego Ariel Aizemberg (Tutor)
  - Proyecto final de carrera
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: scrartcl
citation_package: biblatex
# biblio-style: apa
biblatexoptions: [backend=biber, maxbibnames=999]
papersize: a4
fontsize: 12pt
linestretch: 1.25
geometry: margin=1in
bibliography: [book.bib, packages.bib]
csl: apa.csl
lof: True
link-citations: yes
github-repo: qcho/nerd-pf
description: "Proyecto final de la carrera de ingeniería informática. ITBA."
---

```{r include=FALSE}
library(knitr)
library(tidyverse)
source('./initial_setup.R')
```

\newpage
# Introducción {#intro}

El **Reconocimiento de Entidades Nombradas** (_NER_) es una subtarea del área de _Natural Language Processing_ (_NLP_) que busca extraer **entidades nombradas** en textos no estructurados. Estas entidades son luego clasificadas en categorías predefinidas como los nombres de personas, organizaciones, ubicaciones, expresiones de tiempo, cantidades, valores monetarios, porcentajes, entre otras.

Por ejemplo en el siguiente texto:

>Este es el proyecto final de la carrera Ingeniería Informática de los alumnos Gómez y Orsay para el Instituto Tecnológico de Buenos Aires.

Se pueden detectar 3 entidades:

* **Gómez**: Persona
* **Orsay**: Persona
* **Instituto Tecnológico de Buenos Aires**: Organización

El estado-del-arte de los sistemas _NER_ producen un rendimiento casi humano[@marsh-perzanowski-1998-muc] (cercanos al 95% de _valor-F_).

A pesar de estos altos valores de rendimiento, la industria tiene dificultades para poder capitalizar la efectividad de dichas sistemas y algoritmos.
Es por ello que en este trabajo final hemos tomado la decisión de implementar una plataforma Open Source para revertir esta situación.
