sequenceDiagram;
   participant c as Usuario
   participant a as API
   participant m as MongoDB
   participant r as RabbitMQ
   participant w as Worker
   loop Entrenar
   c->>+a: Pedir texto a entrenar;
   a->>+m: Buscar texto no entrenado;
   m-->>-a: Texto no entrenado;
   a->>+r: Crear tarea de NER;
   activate w;
   w->>r: Pedir tarea;
   r-->>w: Tarea de NER;
   w->>w: Inferir entidades;
   w->>-r: Entidades inferidas;
   r-->>-a: Entidades inferidas;
   a-->>-c: Entidades inferidas;
   c->>c: Corrección de entidades;
   c->>+a: Texto con entidades corregidas;
   a->>+m: Guardar corrección;
   m-->>-a: Guardado;
   a-->>-c: Corregido;
   end
